version: "3.1"
services:
  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
       WORDPRESS_DB_HOST: mysql
       WORDPRESS_DB_USER: yaelzemach
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_DB_PASSWORD: '1234'
  mysql:
    image: mysql:5.7
    ports:
      - 3305:3306
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: wordpress
       MYSQL_USER: yaelzemach
       MYSQL_PASSWORD: '1234'
