version: "3.0"
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      # -PORT=3000 - another contexs
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: password
    restart: always

  myapp:
    image: myapp:1.0
    build: .
    ports:
      - "3000:3000"
    restart: on-failure
    depends_on:
      - mongodb
    environment: 
      MONGO_SERVER: mongodb
      MONGO_USER: root
      MONGO_PASSWD: password
      MONGO_PORT: 27017
    network_mode: host
volumes:
  mongodb-data:
    driver: local